services:
  # Backend API (connects to local database)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      # Override for Docker container to access local database
      - DB_HOST=host.docker.internal
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    network_mode: "bridge"
    extra_hosts:
      - "host.docker.internal:host-gateway"

