name: 'Setup Database'
description: 'Sets up PostgreSQL database with test data for integration tests'
inputs:
  working-directory:
    description: 'Working directory containing .env.test file'
    required: true
    default: './backend'
  db-password:
    description: 'Database password for the user (from secrets)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install PostgreSQL client
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Set up database
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Copy test environment file
        cp .env.test .env
        
        # Read database configuration from .env.test
        export $(grep -v '^#' .env.test | xargs)
      
        echo "Database config: DB_NAME=$DB_NAME, DB_USER=$DB_USER"
        
        # Wait for PostgreSQL to be ready
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        
        # Create user and database
        PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE USER \"$DB_USER\" WITH PASSWORD '$DB_PASSWORD';"
        PGPASSWORD=postgres psql -h localhost -U postgres -c "CREATE DATABASE $DB_NAME OWNER \"$DB_USER\";"
        
        # Create recipes table with updated schema
        PGPASSWORD="$DB_PASSWORD" psql -h localhost -U "$DB_USER" -d "$DB_NAME" -c "
        CREATE TABLE IF NOT EXISTS recipes (
          id SERIAL PRIMARY KEY,
          name VARCHAR(255) NOT NULL,
          category VARCHAR(20) CHECK (category IN ('breakfast', 'lunch', 'dinner', 'snack')),
          main_ingredients JSONB,
          common_ingredients TEXT[] DEFAULT '{}',
          instructions TEXT NOT NULL,
          prep_time INTEGER,
          portions INTEGER
        );"

        # Insert sample recipe with structured ingredients
        PGPASSWORD="$DB_PASSWORD" psql -h localhost -U "$DB_USER" -d "$DB_NAME" -c "
        INSERT INTO recipes (name, category, main_ingredients, common_ingredients, instructions, prep_time, portions) 
        VALUES (
          'Test Pasta', 
          'dinner', 
          '[
            {\"name\": \"pasta\", \"unit\": \"g\", \"quantity\": 250},
            {\"name\": \"tomato\", \"unit\": \"g\", \"quantity\": 500},
            {\"name\": \"onion\", \"unit\": \"pcs\", \"quantity\": 1},
            {\"name\": \"burrata\", \"unit\": \"pcs\", \"quantity\": 1}
          ]'::jsonb,
          ARRAY['salt', 'pepper', 'basil', 'olive', 'garlic'],
          'Cook pasta and add oil',
          15,
          2
        );"
