name: Test BE service

on:
  push:
    branches: [ main, add-workflow-and-structure ]
  pull_request:
    branches: [ main ]

jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.7'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest test_health.py -v


  integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.7'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test server startup
      run: |
        # Start the server in background
        uvicorn main:app --host 127.0.0.1 --port 8000 &
        SERVER_PID=$!
        
        # Wait for server to start
        sleep 5
        
        # Test the health endpoint
        curl -f http://127.0.0.1:8000/health || exit 1
        
        # Stop the server
        kill $SERVER_PID